[www]
; User and group the process will run as
user = test-ssh
group = clp

; Listen on TCP socket
listen = 0.0.0.0:9000

; Allow connections from specific IPs
listen.allowed_clients = 127.0.0.1,172.0.0.0/8

; Process manager
pm = dynamic
pm.max_children = 20
pm.start_servers = 10
pm.min_spare_servers = 5
pm.max_spare_servers = 15
pm.max_requests = 500
pm.max_requests_grace_period = 60s

; Timeout
request_terminate_timeout = 300s
request_slowlog_timeout = 5s

; Logging
slowlog = /var/log/php-fpm/www-slow.log
catch_workers_output = yes
decorate_workers_output = no

; Security
php_admin_value[disable_functions] = pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wifcontinued,pcntl_kill,pcntl_async_signals,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_get_child_status

; Environment variables
env[MYSQL_HOST] = $MYSQL_HOST
env[MYSQL_USER] = $MYSQL_USER
env[MYSQL_PASSWORD] = $MYSQL_PASSWORD
env[MYSQL_DATABASE] = $MYSQL_DATABASE
env[ELASTICSEARCH_HOST] = $ELASTICSEARCH_HOST
env[ELASTICSEARCH_PORT] = $ELASTICSEARCH_PORT
env[REDIS_HOST] = $REDIS_HOST
env[REDIS_PORT] = $REDIS_PORT
env[REDIS_CACHE_DB] = $REDIS_CACHE_DB
env[REDIS_PAGE_CACHE_DB] = $REDIS_PAGE_CACHE_DB
env[REDIS_SESSION_DB] = $REDIS_SESSION_DB
